phaBalloting/Areas/Admin/Controllers/ProjectTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using phaBalloting.Data;
using phaBalloting.Helpers;
using Microsoft.AspNet.Identity;

namespace phaBalloting.Areas.Admin.Controllers
{
    [Authorize]
    public class ProjectTypesController : Controller //UnitTypes
    {
        private phaEntities db = new phaEntities();

        // GET: Admin/UnitTypes
        public ActionResult Index(int? pageNumber)
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            var ProjectTypes = db.ProjectTypes.Where(w => w.IsActive && !w.IsDeleted).Include(u => u.ProjectTypeConfigurations);
            var model = ProjectTypes.Where(w => w.IsActive && !w.IsDeleted).ToList();
            var type= string.IsNullOrEmpty(Request.Form["keywords"]) ? string.Empty : Request.Form["keywords"].ToLower();
            if (type != string.Empty)
            {
                return View(model.Where(x => x.Description.ToLower().Contains(type) || x.TypeName.ToLower().Contains(type)).ToList().ToPagedList(pageNumber ?? 1, 10));
            }
            //else
            //{
            //    return View(model.Where(x => x.UserName.StartsWith(searchString) || searchString == null).ToList().ToPagedList(pageNumber ?? 1, 25));
            //}

            return View(model.ToPagedList(pageNumber ?? 1, 10));
        }

        // GET: Admin/UnitTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectType ProjectTypes = db.ProjectTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (ProjectTypes == null)
            {
                return HttpNotFound();
            }
            return View(ProjectTypes);
        }

        // GET: Admin/UnitTypes/Create
        public ActionResult Create()
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }
            //ViewBag.DataTypeId = new SelectList(db.AttributeDataTypes.Where(w=>!w.IsDeleted && w.IsActive), "Id", "DataTypeName");
            ViewBag.AttributesTypes = db.AttributesTypes.Where(w => w.IsActive && !w.IsDeleted).ToList();

            return View();
        }

        // POST: Admin/UnitTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TypeName,Description,DataTypeId,UserId,EntryDate,ModifiedBy,ModifiedDate,IsActive,IsDeleted")] ProjectType ProjectTypes)
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }

            var attributes = Request.Form["SelectedAttributes"];
            if (string.IsNullOrEmpty(attributes))
            {
                ModelState.AddModelError("", "Please select atleast one attribute to continue.");
            }
            if (ModelState.IsValid)
            {
                ProjectTypes.UserId = User.Identity.GetUserId();
                ProjectTypes.EntryDate = DateTime.Now;
                ProjectTypes.IsActive = true;
                ProjectTypes.IsDeleted = false;
                if (!String.IsNullOrEmpty(attributes))
                {
                    var splittedAttributes = attributes.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    foreach (var attrib in splittedAttributes)
                    {
                        ProjectTypes.ProjectTypeConfigurations.Add(new ProjectTypeConfiguration { AttributeTypeId = int.Parse(attrib), Description = string.Empty, EntryDate = DateTime.Now, IsActive = true, IsDeleted = false, UserId = User.Identity.GetUserId() });
                    }
                }
                db.ProjectTypes.Add(ProjectTypes);

                try
                {
                    db.SaveChanges();
                    UserHelper.WriteActivity("Added Project Type of Id:" + ProjectTypes.Id + " Project Name: " + ProjectTypes.TypeName);
                    return RedirectToAction("Index");
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException invalids)
                {
                    foreach (System.Data.Entity.Validation.DbEntityValidationResult inavlidEntities in invalids.EntityValidationErrors)
                    {

                        foreach (var invalid in inavlidEntities.ValidationErrors)
                        {
                            ModelState.AddModelError(invalid.PropertyName, invalid.ErrorMessage);
                        }
                    }
                }
            }
            ViewBag.AttributesTypes = db.AttributesTypes.Where(w => w.IsActive && !w.IsDeleted).ToList();
            return View(ProjectTypes);
        }

        // GET: Admin/UnitTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.EditRecords))
            {
                return View("NotAuthorize");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectType ProjectTypes = db.ProjectTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();

            if (ProjectTypes == null)
            {
                return HttpNotFound();
            }
            ViewBag.AttributesTypes = db.AttributesTypes.Where(w => w.IsActive && !w.IsDeleted).ToList();
            return View(ProjectTypes);
        }

        // POST: Admin/UnitTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TypeName,Description,DataTypeId,UserId,EntryDate,ModifiedBy,ModifiedOn,IsActive,IsDeleted")] ProjectType ProjectTypes)
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.EditRecords))
            {
                return View("NotAuthorize");
            }

            var attributes = Request.Form["SelectedAttributes"];
            if (string.IsNullOrEmpty(attributes)) {
                ModelState.AddModelError("","Please select atleast one attribute to continue.");
            }
            if (ModelState.IsValid)
            {
                ProjectTypes.ModifiedBy = User.Identity.GetUserId();
                ProjectTypes.ModifiedDate = DateTime.Now;
               var existings= db.ProjectTypeConfigurations.Where(w=>w.PojectTypeId==ProjectTypes.Id);
                foreach (var ex in existings) {
                    db.ProjectTypeConfigurations.Remove(ex);
                }
                ProjectTypes.ProjectTypeConfigurations.Clear();
                if (!String.IsNullOrEmpty(attributes))
                {
                    var splittedAttributes = attributes.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
                    foreach (var attrib in splittedAttributes)
                    {
                        db.ProjectTypeConfigurations.Add(new ProjectTypeConfiguration { PojectTypeId=ProjectTypes.Id, AttributeTypeId = int.Parse(attrib), Description = string.Empty, EntryDate = DateTime.Now, IsActive = true, IsDeleted = false, UserId = User.Identity.GetUserId() });
                    }
                }

                db.Entry(ProjectTypes).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                    UserHelper.WriteActivity("Edited Project Type of Id:" + ProjectTypes.Id + " Project Name: " + ProjectTypes.TypeName);
                    return RedirectToAction("Index");
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException invalids)
                {
                    foreach (System.Data.Entity.Validation.DbEntityValidationResult inavlidEntities in invalids.EntityValidationErrors)
                    {

                        foreach (var invalid in inavlidEntities.ValidationErrors)
                        {
                            ModelState.AddModelError(invalid.PropertyName, invalid.ErrorMessage);
                        }
                    }
                }
            }
            ViewBag.AttributesTypes = db.AttributesTypes.Where(w => w.IsActive && !w.IsDeleted).ToList();
            return View(ProjectTypes);
        }

        // GET: Admin/UnitTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!EnumManager.Modules.ProjectType.IsAuthrozed(EnumManager.Actions.DeleteRecords))
            {
                return View("NotAuthorize");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectType ProjectTypes = db.ProjectTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (ProjectTypes == null)
            {
                return HttpNotFound();
            }

phaBalloting/Areas/Admin/Controllers/UserActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using phaBalloting.Data;
using phaBalloting.Helpers;

namespace phaBalloting.Areas.Admin.Controllers
{
    [Authorize]
    public class UserActivitiesController : Controller
    {
        private phaEntities db = new phaEntities();

        // GET: Admin/UserActivities
        public ActionResult Index(int? pageNumber)
        {
            
            var userActivities = db.UserActivities.ToList().OrderBy(x => x.Id);
            var name = string.IsNullOrEmpty(Request.Form["keywords"]) ? string.Empty : Request.Form["keywords"].ToLower();

            //var location= string.IsNullOrEmpty(Request.Form["ProjectLocation"]) ? string.Empty : Request.Form["ProjectLocation"]; ;
            if (name != string.Empty)
            {
                return View(userActivities.Where(x => x.Description.ToLower().Contains(name) || x.ClientDetail.ToLower().Contains(name) ).ToList().ToPagedList(pageNumber ?? 1, 10));
            }

            return View(userActivities.ToPagedList(pageNumber ?? 1, 10));

        }

        public ActionResult Details(string username)
        {
            string url = Request.QueryString["username"];
            if (username == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserActivity userActivity = db.UserActivities.Where(a=>a.UserId==url).FirstOrDefault();
            if (userActivity == null)
            {
                return HttpNotFound();
            }
            return View(userActivity);
        }

        
        // GET: Admin/UserActivities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserActivity userActivity = db.UserActivities.Find(id);
            if (userActivity == null)
            {
                return HttpNotFound();
            }
            db.UserActivities.Remove(userActivity);
            db.SaveChanges();

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

phaBalloting/Areas/Admin/Views/Users/AssignRole.cshtml
@{
    ViewBag.Title = "AssignRole";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section breadcrumb
{
<li class="breadcrumb-item"><a href="@Url.Action("RoleList", "Users", new { area="admin"})">Roles</a>s1zraaZAA</li>

    <li class="breadcrumb-item active">Assign Role</li>
}
<h2>AssignRole <a style="float:right;" class="btn btn-success" href="@Url.Action("RoleList")">Back to Role list</a></h2>
@{
    var roles = (SelectList)ViewBag.roles;
    var users = (SelectList)ViewBag.users;
}
<label>Select Role</label>
@using (Html.BeginForm()) { 
    @Html.AntiForgeryToken()
<p>
    @Html.DropDownList("rolename", roles)
</p>

<label>Select User</label>
<p>
    @Html.DropDownList("userId", users)
</p>
 
    <input type="submit" />   
}

phaBalloting/Areas/Admin/Views/Users/Authentications.cshtml
@model IEnumerable<phaBalloting.Areas.Admin.Models.AuthenticationModel.authenticationClass>
@{
    ViewBag.Title = "Authentications";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Authentications</h2>
<p id="message" style="height:20px;">
</p>
<div class="row">
    <div class="col-lg-12">
        <a href="@Url.Action("Index")" class="btn btn-success pull-right"><i class="icon-list"></i>Back to User Role List</a>
    </div>
</div>
<table class="table table-hover">
    <tr>
        <th></th>
        <th>View</th>
        <th>Add</th>
        <th>Update</th>
        <th>Delete</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        string ViewRecords = item.ViewRecords == true ? "Checked" : "";
        string AddRecords = item.AddRecords == true ? "Checked" : "";
        string EditRecords = item.EditRecords == true ? "Checked" : "";
        string DeleteRecords = item.DeleteRecords == true ? "Checked" : "";
        <tr>
            <td>
                @Html.Label(item.Description)
            </td>
            <td>
                <label><input type='checkbox' data-id="@item.ID" data-roleid="@item.RoleId" data-formid="@item.FormID" data-col="ViewRecords" @ViewRecords /><span class="lbl"></span></label>
            </td>
            <td>
                <label><input type='checkbox' data-id="@item.ID" data-roleid="@item.RoleId" data-formid="@item.FormID" data-col="AddRecords" @AddRecords /><span class="lbl"></span></label>
            </td>
            <td>
                <label><input type='checkbox' data-id="@item.ID" data-roleid="@item.RoleId" data-formid="@item.FormID" data-col="EditRecords" @EditRecords /><span class="lbl"></span></label>
            </td>
            <td>
                <label><input type='checkbox' data-id="@item.ID" data-roleid="@item.RoleId" data-formid="@item.FormID" data-col="DeleteRecords" @DeleteRecords /><span class="lbl"></span></label>
            </td>

        </tr>
    }
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
    $('input[type=checkbox]').change(function () {
        $('#message').html('');
        //alert(id);
        var Auth = {};
        Auth.FormID = $(this).data('formid');
        Auth.RoleId = $(this).data('roleid');
        var id = $(this).data("id");
        if (parseInt(id) != -1)
            Auth.ID = id;

        $(this).closest('tr').find('input[type=checkbox]').each(function () {
            var col = $(this).data('col');
            var val = $(this).is(':checked');
            //alert(col +"-"+val);
            if (col == 'AddRecords') {
                Auth.AddRecords = val;
            }
            else if (col == 'ViewRecords')
                Auth.ViewRecords = val;
            else if (col == 'EditRecords')
                Auth.EditRecords = val;
            else if (col == 'DeleteRecords')
                Auth.DeleteRecords = val;
        });
        //alert(JSON.stringify({ auth: Auth }));
        $.ajax({
            url: '@Url.Action("SaveOrUpdate")',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify({ auth: Auth }),
            success: function (data) {
                if (data.trim() == 'true') $('#message').html('<div class="alert alert-success"  id="message">success fully stored to data base.</div>');
                else $('#message').html('<div class="alert alert-danger"  id="message">unable to store to data base.</div>');
                location.reload(true);
            },
            error: function (error, code, xhr) { $('#message').html('<div class="alert alert-danger"  id="message">unable to store to data base.</div>'); }
        });
    });
    </script>
}

phaBalloting/Areas/Admin/Views/Users/Create.cshtml
@model phaBalloting.Models.RegisterViewModel
@{
    ViewBag.Title = "";// "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<hgroup class="title">
    <h1>@ViewBag.Title</h1>
    <h2>Create a new user account.</h2>
</hgroup>

@using (Html.BeginForm("Create", "Users", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                <div class="form-group">
                    @Html.Label("Email", htmlAttributes: new { @class = "control-label col-xs-3" })
                    <div class="col-xs-9">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </li>
            <li>
                <div class="form-group">
                    @Html.Label("Password", htmlAttributes: new { @class = "control-label col-xs-3" })
                    <div class="col-xs-9">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
            </li>
            <li>
                <div class="form-group">
                    @Html.Label("Confirm Password", htmlAttributes: new { @class = "control-label col-xs-3" })
                    <div class="col-xs-9">
                        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>
            </li>

            <li>
                <div class="form-group">
                    @Html.Label("Profile Pic", htmlAttributes: new { @class = "control-label col-xs-3" })
                    <div class="col-xs-9">
                        @Html.EditorFor(model => model.ProfilePic, new { htmlAttributes = new {type="file"} })
                        @Html.ValidationMessageFor(model => model.ProfilePic, "", new { @class = "text-danger" })
                    </div>
                </div>
            </li>
        </ol>
        <div class="">
            <div class=" col-xs-12 pr-3">
                <input type="submit" value="Register" class="pull-right btn btn-default" />
            </div>
        </div>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

phaBalloting/Areas/Admin/Views/Users/CreateRole.cshtml
@{
    ViewBag.Title = "CreateRole";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@*@section breadcrumb
{
    <li class="breadcrumb-item"><a href="@Url.Action("Rolelist")">Roles</a></li>

    <li class="breadcrumb-item active">Create Roles</li>
}*@
<h2>Create Role</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    <label>
        Role
    </label>
    <p>
        @{
    string role = ViewBag.rolename;
        }
        @Html.TextBox("RoleName", role)
    </p>
    <p>
        @Html.ValidationMessage("RoleName")
    </p>
    <input type="submit" />
}

phaBalloting/Areas/Admin/Views/Users/Edit.cshtml
@model phaBalloting.Models.UserProfile

@{
    ViewBag.Title = "";// "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<hgroup class="title">
    <h1>@ViewBag.Title</h1>
    <h2>Edit user account.</h2>
</hgroup>

@using (Html.BeginForm("Edit", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.Label("Full Name")
                @Html.TextBoxFor(m => m.FullName)
            </li>
            <li>
                @Html.Label("Email")
                @Html.TextBoxFor(m => m.Email)
            </li>
            <li>
                @Html.Label("Mobile")
                @Html.TextBoxFor(m => m.Mobile)
            </li>
            <li>
                @Html.Label("User Name")
                @Html.TextBoxFor(m => m.UserName)
            </li>
            
            <li>
            <img src="@Model.ProfilePic"  class="img-thumbnail"/>
            </li>
            <li>
                @Html.Label("Profile Pic")
                @Html.TextBox("ProfilePicFile", null, new { type = "file" })
            </li>
            <li>
                @Html.Label("Status")
                @Html.CheckBoxFor(m => m.Status)
            </li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

phaBalloting/Areas/Admin/Views/Users/EditRole.cshtml
@{
    ViewBag.Title = "EditRole";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section breadcrumb
{
<li class="breadcrumb-item"><a href="@Url.Action("Rolelist")">Roles</li>

    <li class="breadcrumb-item active">Edit Roles</li>
}
<h2>Edit Role</h2>
@using (Html.BeginForm())
{
    Html.AntiForgeryToken();
    <label>
        Role
    </label>
    <p>
        @{
    string role = ViewBag.rolename;
        }
        @Html.TextBox("RoleName", role)
    </p>
    <input type="submit" />
}

phaBalloting/Areas/Admin/Views/Users/Index.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<phaBalloting.Models.ApplicationUser>
@using phaBalloting.Helpers;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="page-title">
    <div class="title_left">
        <h3>Application users</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            @using (Html.BeginForm("Index", "Users", FormMethod.Get))
            {<div class="input-group">
                    <input type="text" name="keywords" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div>}
        </div>
    </div>
</div>

<h2> <a style="float:right;" class="btn btn-success" href="@Url.Action("Create")">Add User</a></h2>

<table class="table table-sm">
    <thead>
        <tr>
            <th>Username</th>
            <th>Role</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3"> <b>Records not found </b></td>
            </tr>
        }
        else
        {
            foreach (var profile in Model)
            {

                <tr>
                    <td>@profile.UserName</td>
                    <td>@string.Join(" ,", profile.UserName.GetRoles())</td>
                    <td>
                        <span class="badge badge-success">@(profile.EmailConfirmed ? "Active" : "Inactive") </span>
                    </td>
                    <td>
                        <a href="@Url.Action("Details","Users", new { username = profile.UserName })">Deatils</a> |
                        <a href="@Url.Action("Edit","Users", new { username = profile.UserName })">Edit</a> |
                        <a href="@Url.Action("Delete","Users", new { username = profile.UserName })">Delete</a> | 
                        <a href="@Url.Action("Details","UserActivities", new { username = profile.Id })">Activity</a>
                    </td>
                </tr>
            }

        }
    </tbody>
</table>
@Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
{
    pageNumber,
    option = Request.QueryString["keywords"]
}))

phaBalloting/Areas/Admin/Views/Users/RoleList.cshtml
@{
    ViewBag.Title = "Roles";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@*@section breadcrumb
{

    <li class="breadcrumb-item active">List of Roles</li>
}*@
<div class="page-title">
    <div class="title_left">
        <h3>List of roles</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            @using (Html.BeginForm("Index", "ProjectTypes", FormMethod.Get))
            {<div class="input-group">
                    <input type="text" name="keywords" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div>}
        </div>
    </div>
</div>
<h2> <a style="float:right;" class="btn btn-success" href="@Url.Action("CreateRole")">Create Role</a></h2>



<table class="table">
    <thead>
        <tr>
            <th>S.No</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @{int index = 1;}
        @foreach (var role in (string[])ViewBag.Roles)
        {
            <tr>
                <td>@index</td>
                <td>@role</td>
                <td>
                    <a href="@Url.Action("Authentications", new { role=role })" ><span><img src="~/Areas/Admin/assets/images/index.png" width="20" height="20"/></span> Privileges</a> | 
                    <a href="@Url.Action("UsersInRole", new { role=role })"><span><img src="~/Areas/Admin/assets/images/userInRole.png" width="20" height="20" /></span> Users In role</a> |
                    <a href="@Url.Action("AssignRole", new { role = role })"><span><img src="~/Areas/Admin/assets/images/addUser.png" width="20" height="20" /></span> Add Users In role</a> 
                </td>
            </tr>
            index++;
        }
        
    </tbody>
</table>

phaBalloting/Areas/Admin/Views/Users/UserDetails.cshtml
@{
    ViewBag.Title = "Users Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Users In Role @ViewBag.rolename</h2>



<table class="table">
    <thead>
        <tr>
            <th>S.No</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @{int index = 1;}
        @foreach (var user in (string[])ViewBag.users)
        {
            <tr>
                <td>@index</td>
                <td>@user</td>
                <td>
                    <a href="@Url.Action("UserDetails", new { username = user})">Detials</a> | <a href="@Url.Action("RemoveUserFromRole", new { username = user, role = ViewBag.rolename })">Remove</a>
                </td>
            </tr>
            index++;
        }

    </tbody>
</table>

phaBalloting/Areas/Admin/Views/Users/UsersInRole.cshtml
@{
    ViewBag.Title = "Users In Role";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section breadcrumb
{
    <li class="breadcrumb-item"><a href="@Url.Action("Rolelist")">Roles</li>

    <li class="breadcrumb-item active">Users In Roles</li>
}
<h2>Users In Role @ViewBag.rolename <a style="float:right;" class="btn btn-success" href="@Url.Action("AssignRole", new { role=ViewBag.rolename})">Add User in Role</a></h2>



<table class="table">
    <thead>
        <tr>
            <th>S.No</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @{int index = 1;}
        @foreach (var user in (string[])ViewBag.users)
        {
            <tr>
                <td>@index</td>
                <td>@user</td>
                <td>
                    <a href="@Url.Action("UserDetails", new { username = user})">Detials</a> | <a href="@Url.Action("RemoveUserFromRole", new { username = user, rolename = ViewBag.rolename })">Remove</a>
                </td>
            </tr>
            index++;
        }

    </tbody>
</table>