phaBalloting/Areas/Admin/Controllers/AttributeDataTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using PagedList;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using phaBalloting.Data;
using phaBalloting.Helpers;

namespace phaBalloting.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AttributeDataTypesController : Controller
    {
        
        private phaEntities db = new phaEntities();
        private UserActivity userActivity = new UserActivity();
        // GET: Admin/UnitDataTypes
        public ActionResult Index(int? pageNumber)
        {
            

            string datatypeName = string.IsNullOrEmpty(Request.Form["keywords"]) ? string.Empty : Request.Form["keywords"].ToLower(); //Request.Form["DataTypeName"];
            
            var model = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted).ToList();
            if (datatypeName != string.Empty)
            {
                return View(model.Where(x => x.Description.ToLower().Contains(datatypeName) || x.DataTypeName.ToLower().Contains(datatypeName) ).ToList().ToPagedList(pageNumber ?? 1, 10));
            }

            return View(model.ToPagedList(pageNumber ?? 1, 10));
        }

        // GET: Admin/UnitDataTypes/Details/5
        public ActionResult Details(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AttributeDataType unitDataType = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id==id).FirstOrDefault();
            if (unitDataType == null)
            {
                return HttpNotFound();
            }
            return View(unitDataType);
        }

        // GET: Admin/UnitDataTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/UnitDataTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DataTypeName,DataType,Description,UserId,EntryDate,ModifiedBy,ModifiedDate,IsActive,IsDeleted")] AttributeDataType unitDataType)
        {
            if (ModelState.IsValid)
            {
                unitDataType.UserId = User.Identity.GetUserId();
                unitDataType.EntryDate = DateTime.Now;
                unitDataType.IsActive = true;
                unitDataType.IsDeleted = false;
                db.AttributeDataTypes.Add(unitDataType);
                try {
                    db.SaveChanges();
                    UserHelper.WriteActivity("Added Attribute Data Type with Id: " + unitDataType.Id + "Attribute Type: " + unitDataType.AttributesTypes);
                    return RedirectToAction("Index");

                }
                catch (System.Data.Entity.Validation.DbEntityValidationException invalids) {
                    foreach (System.Data.Entity.Validation.DbEntityValidationResult inavlidEntities in invalids.EntityValidationErrors)
                    {

                        foreach (var invalid in inavlidEntities.ValidationErrors)
                        {
                            ModelState.AddModelError(invalid.PropertyName, invalid.ErrorMessage);
                        }
                    }
                }
            }

            return View(unitDataType);
        }

        // GET: Admin/UnitDataTypes/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AttributeDataType unitDataType = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (unitDataType == null)
            {
                return HttpNotFound();
            }
            return View(unitDataType);
        }

        // POST: Admin/UnitDataTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DataTypeName,DataType,Description,UserId,EntryDate,ModifiedBy,ModifiedDate,IsActive,IsDeleted")] AttributeDataType unitDataType)
        {

            if (ModelState.IsValid)
            {
                unitDataType.ModifiedBy = User.Identity.GetUserId();
                unitDataType.ModifiedDate = DateTime.Now;
                db.Entry(unitDataType).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                    UserHelper.WriteActivity("Edited Attribute Data Type with Id: " + unitDataType.Id + "Attribute Type: " + unitDataType.AttributesTypes);
                    return RedirectToAction("Index");
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException invalids)
                {
                    foreach (System.Data.Entity.Validation.DbEntityValidationResult inavlidEntities in invalids.EntityValidationErrors)
                    {

                        foreach (var invalid in inavlidEntities.ValidationErrors)
                        {
                            ModelState.AddModelError(invalid.PropertyName, invalid.ErrorMessage);
                        }
                    }
                }

            }
            return View(unitDataType);
        }

        // GET: Admin/UnitDataTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AttributeDataType unitDataType = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (unitDataType == null)
            {
                return HttpNotFound();
            }
            return View(unitDataType);
        }

        // POST: Admin/UnitDataTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            AttributeDataType unitDataType = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (unitDataType == null)
            {
                return HttpNotFound();
            }

            unitDataType.IsDeleted = true;
            unitDataType.ModifiedBy = User.Identity.GetUserId();
            unitDataType.ModifiedDate = DateTime.Now;
            db.Entry(unitDataType).State = EntityState.Modified;
            try
            {
                db.SaveChanges();
                UserHelper.WriteActivity("Deleted Attribute Data Type with Id: " + unitDataType.Id + "Attribute Type: " + unitDataType.AttributesTypes);
                return RedirectToAction("Index");
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException invalids)
            {
                foreach (System.Data.Entity.Validation.DbEntityValidationResult inavlidEntities in invalids.EntityValidationErrors)
                {

                    foreach (var invalid in inavlidEntities.ValidationErrors)
                    {
                        ModelState.AddModelError(invalid.PropertyName, invalid.ErrorMessage);
                    }
                }
            }
            return RedirectToAction("Delete", new { id = id });
        }


        // GET: Admin/UnitDataTypes/Delete/5
        public ActionResult UndoDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AttributeDataType unitDataType = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (unitDataType == null)
            {
                return HttpNotFound();
            }
            return View(unitDataType);
        }

        // POST: Admin/UnitDataTypes/Delete/5
        [HttpPost, ActionName("UndoDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult UndoDeleteConfirmed(int id)
        {

            AttributeDataType unitDataType = db.AttributeDataTypes.Where(w => w.IsActive && !w.IsDeleted && w.Id == id).FirstOrDefault();
            if (unitDataType == null)
            {
                return HttpNotFound();
            }

            unitDataType.IsDeleted = false;
            unitDataType.ModifiedBy = User.Identity.GetUserId();
            unitDataType.ModifiedDate = DateTime.Now;
            db.Entry(unitDataType).State = EntityState.Modified;
            try
            {
                db.SaveChanges();
                UserHelper.WriteActivity("Undo Deleted Attribute Data Type with Id: " + unitDataType.Id + "Attribute Type: " + unitDataType.AttributesTypes);
                return RedirectToAction("Index");
                
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException invalids)
            {
                foreach (System.Data.Entity.Validation.DbEntityValidationResult inavlidEntities in invalids.EntityValidationErrors)
                {

                    foreach (var invalid in inavlidEntities.ValidationErrors)
                    {
                        ModelState.AddModelError(invalid.PropertyName, invalid.ErrorMessage);
                    }
                }
            }
            return RedirectToAction("UndoDelete", new { id = id });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {

phaBalloting/Areas/Admin/Views/AttributeDataTypes/Create.cshtml
@model phaBalloting.Data.AttributeDataType

@{
    ViewBag.Title = "Create";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }

}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UnitDataType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Data Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataTypeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataTypeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Data Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

phaBalloting/Areas/Admin/Views/AttributeDataTypes/Delete.cshtml
@model phaBalloting.Data.AttributeDataType

@{
    ViewBag.Title = "Delete";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }

}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UnitDataType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Data Type Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataTypeName)
        </dd>

        <dt>
            @Html.DisplayName("Data Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataType)
        </dd>

        <dt>
            @Html.DisplayName("Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayName("User Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayName("Entry Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryDate)
        </dd>

        <dt>
            @Html.DisplayName("Modified By")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayName("Modified Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayName("IsActive")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

phaBalloting/Areas/Admin/Views/AttributeDataTypes/Details.cshtml
@model phaBalloting.Data.AttributeDataType

@{
    ViewBag.Title = "Details";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }

}

<style>
    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(odd) {
            background-color: #27ae31;
            color: #fff;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #0f5e0e;
            color: white;
        }
</style>

<h2>Details</h2>

<div>
    <h4>UnitDataType</h4>
    <hr />
    <center>
        <table id="customers">
            <tr>
                <th>
                    @Html.DisplayName("Data Type Name")
                </th>
                <td>
                    @Html.DisplayFor(model => model.DataTypeName)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Data Type")
                </th>

                <td>
                    @Html.DisplayFor(model => model.DataType)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Description")
                </th>

                <td>
                    @Html.DisplayFor(model => model.Description)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("User Id")
                </th>

                <td>
                    @Html.DisplayFor(model => model.UserId)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Entry Date")
                </th>

                <td>
                    @Html.DisplayFor(model => model.EntryDate)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Modified By")
                </th>

                <td>
                    @Html.DisplayFor(model => model.ModifiedBy)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Modified Date")
                </th>

                <td>
                    @Html.DisplayFor(model => model.ModifiedDate)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("IsActive")
                </th>

                <td>
                    @Html.DisplayFor(model => model.IsActive)
                </td>
            </tr>
        </table>
    </center>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

phaBalloting/Areas/Admin/Views/AttributeDataTypes/Edit.cshtml
@model phaBalloting.Data.AttributeDataType

@{
    ViewBag.Title = "Edit";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }

}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>UnitDataType</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.EntryDate)
    @Html.HiddenFor(model => model.IsDeleted)


    <div class="form-group">
        @Html.Label("Data Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataTypeName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataTypeName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Data Type", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataType, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DataType, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.Label("IsActive", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

phaBalloting/Areas/Admin/Views/AttributeDataTypes/Index.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<phaBalloting.Data.AttributeDataType>

@{
    ViewBag.Title = "Index";
    if(Request.IsAjaxRequest())
    {
        Layout = null;
    }
}

<div class="page-title">
    <div class="title_left">
        <h3>List of attributes data types</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            @using (Html.BeginForm("Index", "AttributeDataTypes", FormMethod.Get))
            {<div class="input-group">
                    <input type="text" name="keywords" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                </div>}
        </div>
    </div>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Data Type Name")
            </th>
            <th>
                @Html.DisplayName("Data Type")
            </th>
            <th>
                @Html.DisplayName("Description")
            </th>
            <th>
                @Html.DisplayName("IsActive")
            </th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="4"> <b>Records not found </b></td>
        </tr>
}
else
{
    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DataTypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
}

    </table>

@Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
{
    pageNumber,
    Keywords = Request.QueryString["keywords"]
}))