phaBalloting/Areas/Admin/Controllers/DBMaintananceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace phaBalloting.Areas.Admin.Controllers
{
    public class DBMaintananceController : Controller
    {
        // GET: Admin/DBMaintanance
        public ActionResult Backup()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Backup")]
        public string BackupData()
        {
            if (Helpers.DBMaintanance.Backup(Server.MapPath("~/Content/Backup/DatabaseBackup_" + DateTime.Now.ToString("dd_MMM_yyyy_hh_mm_tt") + ".bak")))
                return "successfully created backup of database with Name: DatabaseBackup_" + DateTime.Now.ToString("dd_MMM_yyyy_hh_mm_tt") + ".bak";

            return "unable to create backup of database";
        }

        public ActionResult Restore()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Restore")]
        public bool RestoreData(string path)
        {
            Helpers.DBMaintanance.Restore(Server.MapPath("~/Content/Backup/"+path));
            return false;
        }
    }
}

phaBalloting/Areas/Admin/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using phaBalloting.Data;
using PagedList;
using Microsoft.AspNet.Identity;
using phaBalloting.Helpers;

namespace phaBalloting.Areas.Admin.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private phaEntities db = new phaEntities();

        // GET: Admin/Events
        public ActionResult Index(int? pageNumber)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            var model=db.Events.ToList();
            var name= string.IsNullOrEmpty(Request.Form["keywords"]) ? string.Empty : Request.Form["keywords"].ToLower();
            var eventLocation = string.IsNullOrEmpty(Request.Form["EventLocation"]) ? string.Empty : Request.Form["EventLocation"];
            if (name != string.Empty)
            {
                return View(model.Where(x => x.EventName.ToLower().Contains(name) || x.EventLocation.ToLower().Contains(name)).ToList().ToPagedList(pageNumber ?? 1, 10));
            }
            else
            {
                return View(model.ToPagedList(pageNumber ?? 1, 10));
            }
        }

        // GET: Admin/Events/Details/5
        public ActionResult Details(int? id)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Admin/Events/Create
        public ActionResult Create()
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }
            return View();
        }

        // POST: Admin/Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EventName,EventLocation,HeldDate,UserId,EntryDate,LastModifiedOn,LastModifiedBy")] Event @event)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }

            @event.EntryDate = DateTime.Now;
            
            @event.UserId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                UserHelper.WriteActivity("Event Added of Id: " + @event.Id + " Name: " + @event.EventName);
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Admin/Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.EditRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Admin/Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Event @event)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.EditRecords))
            {
                return View("NotAuthorize");
            }

            @event.LastModifiedOn = DateTime.Now;
            @event.LastModifiedBy = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                UserHelper.WriteActivity("Event Modified of Id: " + @event.Id + " Name: " + @event.EventName);
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Admin/Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.DeleteRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Admin/Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!EnumManager.Modules.Events.IsAuthrozed(EnumManager.Actions.DeleteRecords))
            {
                return View("NotAuthorize");
            }

            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            UserHelper.WriteActivity("Event Deleted of Id: " + id + " Name: " + @event.EventName);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

phaBalloting/Areas/Admin/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using PagedList;
using System.Data.Entity.Validation;
using System.Web.Mvc;
using phaBalloting.Data;
using Microsoft.AspNet.Identity;
using OfficeOpenXml;
using System.IO;
using OfficeOpenXml.Drawing;
using phaBalloting.Helpers;

namespace phaBalloting.Areas.Admin.Controllers
{
    [Authorize]
    public class MembersController : Controller
    {
        private phaEntities db = new phaEntities();

        // GET: Admin/Members
        public ActionResult Index(int? pageNumber)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            List<Member> model = new List<Member>();
            var name = string.IsNullOrEmpty(Request["keywords"]) ? string.Empty : Request["keywords"].ToLower(); 
            if (name != string.Empty)
            {
                model = db.Members.Where(w => w.IsActive && !w.IsDeleted).ToList().Where(w=>w.Cnic.ToLower().Contains(name) || w.EmailAddress.ToLower().Contains(name) || w.FatherName.ToLower().Contains(name)|| w.HomeTelephone.ToLower().Contains(name) || w.HusbandName.ToLower().Contains(name) || w.NameOfOfficer.ToLower().Contains(name) || w.OfficeAddress.ToLower().Contains(name) || w.OfficeStatus.ToLower().Contains(name) || w.OfficeTelephone.ToLower().Contains(name) || w.OldMFormNo.ToLower().Contains(name) || w.PermanentAddress.ToLower().Contains(name) || w.PostHeld.ToLower().Contains(name) ).ToList();
            }
            
            else
            {
                model = db.Members.Where(w => w.IsActive && !w.IsDeleted).ToList();
            }

            return View(model.ToPagedList(pageNumber ?? 1, 10));
        }

        // GET: Admin/Members/Details/5
        public ActionResult Details(int? id)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Admin/Members/Create
        public ActionResult Create()
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }
            ViewBag.BPS= new SelectList(db.BPSLists, "Id", "BPS");

            return View();
        }

        // POST: Admin/Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member member, HttpPostedFileBase ImageUrl)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }

            if (ModelState.IsValid)
            {
                member.IsActive = true;
                member.IsDeleted = false;
                member.UserId = User.Identity.GetUserId();
                member.EntryDate = DateTime.Now;
                member.BPSId = int.Parse(Request.Form["BPS"]);
                member.ImageUrl = SaveMemberPic(ImageUrl, member.Cnic);
                db.Members.Add(member);

                try
                {
                    db.SaveChanges();
                    UserHelper.WriteActivity("Added Member with Id: " + member.Id + "Name: " + member.NameOfOfficer);
                }
                catch (Exception ex)
                { ex.ToString(); }
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Admin/Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.EditRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            ViewBag.BPS = new SelectList(db.BPSLists, "Id", "BPS");
            return View(member);
        }

        // POST: Admin/Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OldMFormNo,NameOfOfficer,FatherName,HusbandName,Cnic,OfficeName,OfficeStatus,DateOfJoiningService,PostHeld,OccutionalGroup,DateOfBirth,OfficeAddress,PermanentAddress,HomeTelephone,EmailAddress,ImageUrl,OfficeTelephone,Mobile")] Member member, HttpPostedFileBase NewImage)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.EditRecords))
            {
                return View("NotAuthorize");
            }

            if (ModelState.IsValid)
            {
                member.ModifiedBy = User.Identity.GetUserId();
                member.ModfiedOn= DateTime.Now;
                member.ImageUrl = SaveMemberPic(NewImage, member.Cnic);
                db.Entry(member).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();

                    UserHelper.WriteActivity("Edited Member with id " + member.Id + " Name: " + member.NameOfOfficer);
                }
                catch { }
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Admin/Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.DeleteRecords))
            {
                return View("NotAuthorize");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Admin/Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!EnumManager.Modules.Members.IsAuthrozed(EnumManager.Actions.DeleteRecords))
            {
                return View("NotAuthorize");
            }

            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            try
            {
                db.SaveChanges();
                UserHelper.WriteActivity("Deleted Member with id " + id + " Name: " + member.NameOfOfficer);
            }
            catch { }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ImportExcel()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult ImportExcel(HttpPostedFileBase file)
        {
            if (!EnumManager.Modules.Projects.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }

            DataSet ds = new DataSet();
            DataTable datatab = new DataTable();

            if (file != null && file.ContentLength > 0)
            {
                if (file.FileName.EndsWith(".xls") || file.FileName.EndsWith(".xlsx"))
                {
                    FileInfo f = new FileInfo(file.FileName);
                    
                    var exvelPckg = new OfficeOpenXml.ExcelPackage(f, true).Workbook.Worksheets.FirstOrDefault();

                    var start = exvelPckg.Dimension.Start;
                    var end = exvelPckg.Dimension.End;
                    
                    datatab = WorksheetToDataTable(exvelPckg.Workbook.Worksheets.FirstOrDefault());

                    int result = 0;

                    string ErrorPath = Server.MapPath("~/Content/") + DateTime.Now.ToString("yyyyMMddhhmmss") + System.IO.Path.GetFileNameWithoutExtension(Request.Files["file"].FileName) + ".txt";
                    StreamWriter sw = new StreamWriter(ErrorPath, true);

                    for (int i = start.Row; i < end.Row; i++)
                    {

                        DataRow crow = datatab.Rows[i];
                        

                        Member member = new Member();

                        if (crow[0].ToString().Trim() != "n/a")
                        {
                            if (int.TryParse(crow[0].ToString().Trim(), out result) && (i >= 3))
                            {

                                member.NameOfOfficer = string.IsNullOrEmpty(crow[1].ToString().Trim()) ? string.Empty : crow[1].ToString().Trim();
                                member.FatherName = string.IsNullOrEmpty(crow[2].ToString().Trim()) ? string.Empty : crow[2].ToString().Trim().Trim();
                                //member.HusbandName = string.IsNullOrEmpty(crow[2].ToString().Trim()) ? string.Empty : crow[2].ToString().Trim();

phaBalloting/Areas/Admin/Views/Dashboard/Index.cshtml
@model IEnumerable<phaBalloting.Data.Event>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="row">
    <div class="col-sm-6 col-lg-3">
        <div class="card text-white bg-primary">
            <div class="card-body pb-0">
                <div class="btn-group float-right">
                    <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="icon-settings"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="@Url.Action("Index","Members")">View Members</a>
                        <a class="dropdown-item" href="@Url.Action("Create","Members")">Add New Member</a>
                        <a class="dropdown-item" href="#">Print List</a>
                    </div>
                </div>
                <h4 class="mb-0">9.823</h4>
                <p>Members</p>
            </div>
            <div class="chart-wrapper px-3" style="height:70px;">
                <canvas id="card-chart1" class="chart" height="70"></canvas>
            </div>
        </div>
    </div>
    <!--/.col-->

    <div class="col-sm-6 col-lg-3">
        <div class="card text-white bg-info">
            <div class="card-body pb-0">
                <div class="btn-group float-right">
                    <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="icon-settings"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="@Url.Action("Index","Projects")">View Projects</a>
                        <a class="dropdown-item" href="@Url.Action("Create","Projects")">Add New Project</a>
                        <a class="dropdown-item" href="#">Print List</a>
                    </div>
                </div>
                <h4 class="mb-0">9.823</h4>
                <p>Total Projects</p>
            </div>
            <div class="chart-wrapper px-3" style="height:70px;">
                <canvas id="card-chart2" class="chart" height="70"></canvas>
            </div>
        </div>
    </div>
    <!--/.col-->

    <div class="col-sm-6 col-lg-3">
        <div class="card text-white bg-warning">
            <div class="card-body pb-0">
                <div class="btn-group float-right">
                    <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="icon-settings"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="@Url.Action("Index","Events")">View Events</a>
                        <a class="dropdown-item" href="@Url.Action("Create","Events")">Add New Event</a>
                        <a class="dropdown-item" href="#">Print List</a>
                    </div>
                </div>
                <h4 class="mb-0">9.823</h4>
                <p>Events</p>
            </div>
            <div class="chart-wrapper" style="height:70px;">
                <canvas id="card-chart3" class="chart" height="70"></canvas>
            </div>
        </div>
    </div>
    <!--/.col-->

    <div class="col-sm-6 col-lg-3">
        <div class="card text-white bg-danger">
            <div class="card-body pb-0">
                <div class="btn-group float-right">
                    <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="icon-settings"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="@Url.Action("Index","Users")">View Users</a>
                        <a class="dropdown-item" href="@Url.Action("Create","Users")">Add New User</a>
                        <a class="dropdown-item" href="#">Print List</a>
                    </div>
                </div>
                <h4 class="mb-0">9.823</h4>
                <p>Users</p>
            </div>
            <div class="chart-wrapper px-3" style="height:70px;">
                <canvas id="card-chart4" class="chart" height="70"></canvas>
            </div>
        </div>
    </div>
    <!--/.col-->
</div>