phaBalloting/Areas/Admin/Controllers/BallotingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using phaBalloting.Data;
using PagedList;
using phaBalloting.Areas.Admin.Models;
using phaBalloting.Helpers;


namespace phaBalloting.Areas.Admin.Controllers
{
   
    [Authorize]
    public class BallotingsController : Controller
    {
        private phaEntities db = new phaEntities();
        private BallotingModel ballotModel = new BallotingModel();

        // GET: Admin/Ballotings
        public ActionResult Index()
        {
            if (!EnumManager.Modules.Balloting.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "Id", "ProjectName");

            ViewBag.EventID = new SelectList(db.Events, "Id", "EventName");

            //var ballotings = db.Ballotings.Include(b => b.Event).Include(b => b.Member).Include(b => b.PojectUnit).ToList().OrderBy(x=>x.Id);
            //var name = string.IsNullOrEmpty(Request.Form["keywords"]) ? string.Empty : Request.Form["keywords"].ToLower();

            ////var location= string.IsNullOrEmpty(Request.Form["ProjectLocation"]) ? string.Empty : Request.Form["ProjectLocation"]; ;
            //if (name != string.Empty)
            //{
            //    return View(ballotings.Where(x => x.Member.NameOfOfficer.ToLower().Contains(name) || x.Event.EventName.ToLower().Contains(name) || x.PojectUnit.Project.ProjectName.ToLower().Contains(name)).ToList().ToPagedList(pageNumber ?? 1, 10));
            //}
            //ballotings.ToPagedList(pageNumber ?? 1, 10)
            return View(new DataTable());
            
        }

        [HttpPost]
        public ActionResult Index(int EventId,int ProjectId, int? pageNumber)
        {
            //PagedList<DataRow> list = new PagedList<DataRow>(table.AsEnumerable(), pageNumber.Value, 20);
            string keywords = Request["keywords"];
            string field = Request["field"];
            string filters = string.Empty;
            if(!string.IsNullOrEmpty(field) && !string.IsNullOrEmpty(keywords))
            {
                filters =" "+ field  + " Like '%" + keywords + "%'";
                UserHelper.WriteActivity("Searched balloting for Member: " + field + " Project: " + keywords);

            }
            DataTable table = new BallotingFinalResults(EventId, ProjectId,0,filters).GetData();
            ViewBag.ProjectID = new SelectList(db.Projects, "Id", "ProjectName");

            ViewBag.EventID = new SelectList(db.Events, "Id", "EventName");

            return View(table);
        }
            // GET: Admin/Ballotings/Details/5
            public ActionResult Details(int? id)
        {
            if (!EnumManager.Modules.Balloting.IsAuthrozed(EnumManager.Actions.ViewRecords))
            {
                return View("NotAuthorize");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Balloting balloting = db.Ballotings.Find(id);
            if (balloting == null)
            {
                return HttpNotFound();
            }
            return View(balloting);
        }

        // GET: Admin/Ballotings/Create
        public ActionResult Create()
        {
            if (!EnumManager.Modules.Balloting.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }
            ViewBag.ProjectID = new SelectList(db.Projects, "Id", "ProjectName");

            ViewBag.EventID = new SelectList(db.Events, "Id", "EventName");
            return View();
        }

        
        // POST: Admin/Ballotings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(int ProjectID, int EventID )
        {

            if (!EnumManager.Modules.Balloting.IsAuthrozed(EnumManager.Actions.AddRecords))
            {
                return View("NotAuthorize");
            }
            if (Request.Form["BallotingType"] == null || string.IsNullOrEmpty(Request.Form["BallotingType"]))
            {
                ModelState.AddModelError("", "Invalid balloting type selected for balloting.");
                return View();
            }

            string ballotingType = Request.Form["BallotingType"];
            List<string> ballotingTypes = new List<string> { EnumManager.ballotinTypes.run.ToString(), EnumManager.ballotinTypes.rerun.ToString(), EnumManager.ballotinTypes.runwaiting.ToString()};
            if (!ballotingTypes.Contains(ballotingType))
            {
                ModelState.AddModelError("", "Invalid Balloting type selected for balloting.");
                return View();
            }

            EnumManager.ballotinTypes currentBallotingType = (EnumManager.ballotinTypes)Enum.Parse(typeof(EnumManager.ballotinTypes), ballotingType);

            int projectId = int.Parse(Request.Form["ProjectID"]);
            
            var CurrentProject = db.Projects.Where(w => w.Id == projectId).FirstOrDefault();
            if (CurrentProject == null)
            {
                ModelState.AddModelError("","Invalid Project selected for balloting.");
               
            }
            int eventId = int.Parse(Request.Form["EventID"]);
            var CurrentEvent = db.Events.Where(w => w.Id == eventId).FirstOrDefault();
            if (CurrentEvent == null)
            {
                ModelState.AddModelError("", "Invalid Event selected for balloting.");
                
            }

            List<PojectUnit> projunitList = new List<PojectUnit>();


            if (currentBallotingType == EnumManager.ballotinTypes.run || currentBallotingType == EnumManager.ballotinTypes.rerun)
                projunitList = db.PojectUnits.Where(x => x.Project.Id == projectId).ToList();
            else if (currentBallotingType == EnumManager.ballotinTypes.runwaiting)
                projunitList = db.PojectUnits.Where(x => x.Project.Id == projectId && x.Ballotings.Where(b => b.CancelledBallotings.Count > 0 && b.EventID == eventId).Count() > 0 && x.Ballotings.Where(b => b.CancelledBallotings.Count == 0 && b.EventID == eventId).Count() == 0).ToList();

            if (projunitList.Count() == 0)
            {
                ModelState.AddModelError("", "No Applicable Units found in Selected Project.");
            }
            var projectBPSGroup = db.BPSProjects.Where(x => x.ProjectId == projectId).ToList().Select(s => s.BPSList.BPS.ToLower().Trim()).ToList();
            if(projectBPSGroup.Count==0)
            {
                ModelState.AddModelError("", "No BPS Included for Selected Project.");
            }
            List<Member> membersToBeIncluded = new List<Member>();
            if (currentBallotingType == EnumManager.ballotinTypes.run || currentBallotingType == EnumManager.ballotinTypes.rerun)
                membersToBeIncluded = db.Members.Where(w => w.Ballotings.Count() == 0 && w.IsActive && !w.IsDeleted).ToList().Where(w => projectBPSGroup.Contains(w.BPSList.BPS.Trim().ToLower())).ToList();
            else if (currentBallotingType == EnumManager.ballotinTypes.runwaiting)
                membersToBeIncluded = db.Members.Where(w => w.Ballotings.Count() == 0 && w.WaitingMembers.Where(ww => ww.ProjectID == projectId && ww.EventID == eventId).Count() > 0 && w.IsActive && !w.IsDeleted).ToList().Where(w => projectBPSGroup.Contains(w.BPSList.BPS.Trim().ToLower())).ToList();

            if (membersToBeIncluded.Count == 0)
            {
                ModelState.AddModelError("", "No Members found for Selected Project.");
            }
           

            var waitingPercent = db.phaConfigurations.Where(w => w.ConfigKey == "PercentageToBeWaited").FirstOrDefault();
            if (waitingPercent == null) {
                ModelState.AddModelError("", "Percentage for waiting list is not defined.");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            double percent = double.Parse(waitingPercent.ConfigValue);
            double percentage = percent / 100 ;

            if (currentBallotingType == EnumManager.ballotinTypes.run || currentBallotingType == EnumManager.ballotinTypes.rerun)
            {
                var existings = db.Ballotings.Where(w => w.PojectUnit.PojectId == projectId && w.EventID == EventID).Select(s => s.Id).ToArray();
                if (existings.Count() > 0)
                {
                    db.Ballotings.RemoveRange(db.Ballotings.Where(r => existings.Contains(r.Id)));
                    try
                    {
                        db.SaveChanges();
                    }
                    catch
                    {
                        ModelState.AddModelError("", "Unable to remove previous balloting results.");
                    }
                }
            }
            if (ModelState.IsValid)
            {
                if (ballotModel.AllocationBallots(membersToBeIncluded, projunitList, percentage, eventId))
                {
                    UserHelper.WriteActivity("Performed balloting for Project: " + CurrentProject.ProjectName + " Event: " + CurrentEvent.EventName);

                    DataTable table = new BallotingFinalResults(CurrentEvent.Id, CurrentProject.Id).GetData();

                    return View("Index", table);
                }
            }

            
            //ViewBag.EventID = events;
            ViewBag.EventID = new SelectList(db.Events, "Id", "EventName", eventId);
            ViewBag.ProjectID = new SelectList(db.Projects, "Id", "ProjectName", projectId);

phaBalloting/Areas/Admin/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;

using System.Data;
namespace phaBalloting.Areas.Admin.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Admin/Reports
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Reports
        public FileResult SuccessFullMembers(int eventid = 0, int projectId = 0, int memberId = 0,string reportType="success")
        {
            DataTable table = new phaBalloting.Areas.Admin.Models.BallotingFinalResults(eventid, projectId, memberId,"",reportType).GetData();
            if (table.Columns.Contains("Floor")) table.Columns["Floor"].ColumnName = "c1";
            if (table.Columns.Contains("Flat No")) table.Columns["Flat No"].ColumnName = "c2";

            if (table.Columns.Contains("OldMFormNo")) table.Columns["OldMFormNo"].ColumnName = "MemberNo";

            if (table.Columns.Contains("NameOfOfficer")) table.Columns["NameOfOfficer"].ColumnName = "MemberName";
            string title = reportType == "success" ? "List of Successfull Members" : "List of Cancelled Members";
            var reportViewModel = new phaBalloting.Areas.Admin.Models.ReportViewModel()
            {
                FileName = "~/Content/reports/SuccessfullReport.rdlc",
                //LeftMainTitle = "ABC Company Name",
                //LeftSubTitle = "DEF Department Name",
                //RightMainTitle = "اسم الشركة",
                //RightSubTitle = "اسم القسم",
                Name = "Statistical Report",
                //ReportDate = DateTime.Now,
                Logo = "~/Content/logo.jpg",
                ReportTitle = title,
                SubTitle = " ",
                Contact = " ",
                ReportLanguage = "en-US",
                Format = phaBalloting.Areas.Admin.Models.ReportViewModel.ReportFormat.PDF,
                UserNamPrinting = "",
                ViewAsAttachment = false,
            };
            //adding the dataset information to the report view model object
            reportViewModel.ReportDataSets.Add(new phaBalloting.Areas.Admin.Models.ReportViewModel.ReportDataSet() { Data = table, DatasetName = "DataSet1" });
            return File(reportViewModel.RenderReport(), reportViewModel.LastmimeType);

        }

        public FileResult FailureList(int eventid = 0, int projectId = 0)
        {
            var db = new Data.phaEntities();
             var events = db.Events.Where(w => w.Id == eventid).FirstOrDefault();

            var project = db.Projects.Where(w => w.Id == projectId).FirstOrDefault();


            var data = db.Members.Where(w => w.Ballotings.Count() == 0).ToList().Select(s => new { MemberNo = s.OldMFormNo, MemberName = s.NameOfOfficer,CNIC= s.Cnic, s.BPSList.BPS, EventName = events.EventName, EventLocation = events.EventLocation, HeldDate = events.EntryDate, ProjectName = project.ProjectName, ProjectLocation = project.ProjectLocation, ProjectDescription = project.Description });
            
            var reportViewModel = new phaBalloting.Areas.Admin.Models.ReportViewModel()
            {
                FileName = "~/Content/reports/MemberReport.rdlc",
                //LeftMainTitle = "ABC Company Name",
                //LeftSubTitle = "DEF Department Name",
                //RightMainTitle = "اسم الشركة",
                //RightSubTitle = "اسم القسم",
                Name = "Statistical Report",
                //ReportDate = DateTime.Now,
                Logo = "~/Content/logo.jpg",
                ReportTitle = "List of Failure Members",
                SubTitle = " ",
                Contact = " ",
                ReportLanguage = "en-US",
                Format = phaBalloting.Areas.Admin.Models.ReportViewModel.ReportFormat.PDF,
                UserNamPrinting = "",
                ViewAsAttachment = false,
            };
            //adding the dataset information to the report view model object
            reportViewModel.ReportDataSets.Add(new phaBalloting.Areas.Admin.Models.ReportViewModel.ReportDataSet() { Data = data, DatasetName = "DataSet1" });
            return File(reportViewModel.RenderReport(), reportViewModel.LastmimeType);

        }

        public FileResult WaitingList(int eventid = 0, int projectId = 0)
        {
            var db = new Data.phaEntities();
            var events = db.Events.Where(w => w.Id == eventid).FirstOrDefault();

            var project = db.Projects.Where(w => w.Id == projectId).FirstOrDefault();


            var data = db.Members.Where(w => w.Ballotings.Count() == 0).ToList().Select(s => new { MemberNo = s.OldMFormNo, MemberName = s.NameOfOfficer, CNIC = s.Cnic, s.BPSList.BPS, EventName = events.EventName, EventLocation = events.EventLocation, HeldDate = events.EntryDate, ProjectName = project.ProjectName, ProjectLocation = project.ProjectLocation, ProjectDescription = project.Description });

            var reportViewModel = new phaBalloting.Areas.Admin.Models.ReportViewModel()
            {
                FileName = "~/Content/reports/MemberReport.rdlc",
                //LeftMainTitle = "ABC Company Name",
                //LeftSubTitle = "DEF Department Name",
                //RightMainTitle = "اسم الشركة",
                //RightSubTitle = "اسم القسم",
                Name = "Statistical Report",
                //ReportDate = DateTime.Now,
                Logo = "~/Content/logo.jpg",
                ReportTitle = "Waiting List",
                SubTitle = " ",
                Contact = " ",
                ReportLanguage = "en-US",
                Format = phaBalloting.Areas.Admin.Models.ReportViewModel.ReportFormat.PDF,
                UserNamPrinting = "",
                ViewAsAttachment = false,
            };
            //adding the dataset information to the report view model object
            reportViewModel.ReportDataSets.Add(new phaBalloting.Areas.Admin.Models.ReportViewModel.ReportDataSet() { Data = data, DatasetName = "DataSet1" });
            return File(reportViewModel.RenderReport(), reportViewModel.LastmimeType);

        }
    }
}

phaBalloting/Areas/Admin/Views/Ballotings/Delete.cshtml
@model phaBalloting.Data.Balloting

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Balloting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Event Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.EventName)
        </dd>

        <dt>
            @Html.DisplayName("Name of Officer")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Member.NameOfOfficer)
        </dd>

        <dt>
            @Html.DisplayName("Project Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PojectUnit.Project.ProjectName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

phaBalloting/Areas/Admin/Views/Ballotings/Details.cshtml
@model phaBalloting.Data.Balloting

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<style>
    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(odd) {
            background-color: #27ae31;
            color: #fff;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #0f5e0e;
            color: white;
        }
</style>


<h2>Details</h2>

<div>
    <h4>Balloting</h4>
    <hr />
    <center>
        <table id="customers">
            <tr>
                <th>
                    @Html.DisplayName("Event Name")
                </th>

                <td>
                    @Html.DisplayFor(model => model.Event.EventName)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Name of Officer")
                </th>

                <td>
                    @Html.DisplayFor(model => model.Member.NameOfOfficer)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayName("Project Name")
                </th>

                <td>
                    @Html.DisplayFor(model => model.PojectUnit.Project.ProjectName)
                </td>
            </tr>
        </table>
    </center>

   
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

phaBalloting/Areas/Admin/Views/Ballotings/Index.cshtml
@using PagedList.Mvc;
@using PagedList;

@model System.Data.DataTable

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string[] columnsToExclude = new string[] {"BallotingId", "EventName", "EventLocation", "ProjectName", "TypeName", "ProjectLocation", "TotalApplicableUnits", "EntryDate", "EventHeldDate" };

}
<div id="loader" style="display:none; position:absolute;left:0;top:0;bottom:0;right:0; background-color:rgba(0,0,0,.5);z-index:999999;">
    <span class="spinner" style="display:table;height:100%; ">
        <span style="display:table-cell; vertical-align:middle;text-align:center;"><i class="fa fa-5x fa-spinner fa-spin"></i>
        </span>
    </span>
</div>
<div class="page-title">
    <div class="title_left">
        <h3>Balloting Result</h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            @using (Html.BeginForm("Index", "Ballotings", FormMethod.Post))
    {
                @Html.Hidden("ProjectID")
                @Html.Hidden("EventID")
                <select name="field" class="form-control">
            <option value="dbo.Members.OldMFormNo">Form No</option>
            <option value="dbo.Members.NameOfOfficer">Member name</option>
            <option value="dbo.Members.Cnic">CNIC</option>
        </select>
        <div class="input-group">

            <input type="text" name="keywords" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go!</button>
            </span>
        </div>}
        </div>
    </div>
</div>


<div class="form-horizontal">
    @using (Html.BeginForm())
    {

        <div class="form-group">
            @Html.Label("Event Name", htmlAttributes: new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.DropDownList("EventID", null, new { @class = "form-control" })
                @Html.ValidationMessage("EventId", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Project Name", htmlAttributes: new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @*@Html.DropDownList("ProjectID", null, new { @class = "form-control" })*@
                <select id="ProjectID" name="ProjectID" class="form-control"></select>
                @Html.ValidationMessage("ProjectId", new { @class = "text-danger" })
            </div>
        </div><div class="form-group">
            <label class="control-label col-xs-12">.</label>
            <button id="viewresult" type="submit" class="btn btn-small btn-info">View Results</button>
           </div>
              <div class="col-xs-12">
                  <label class="control-label col-xs-12">.</label>
                  @Html.ActionLink("Successfull Members Printable Report (pdf)", "SuccessFullMembers", "Reports", new { area = "admin", eventid = 0, projectId = 0, memberId = 0 }, new { @class = "btn-report btn btn-small btn-success pull-left", id = "btn-report" })
                  @Html.ActionLink("Waiting List Printable Report (pdf)", "WaitingList", "Reports", new { area = "admin", eventid = 0, projectId = 0 }, new { @class = "btn-report btn btn-small btn-info pull-left", id = "btn-report" })
                  @Html.ActionLink("Failure List Printable Report (pdf)", "FailureList", "Reports", new { area = "admin", eventid = 0, projectId = 0 }, new { @class = "btn-report btn btn-small btn-danger pull-left", id = "btn-report" })
                  @Html.ActionLink("Canceled List Printable Report (pdf)", "SuccessFullMembers", "Reports", new { area = "admin", eventid = 0, projectId = 0, reportType = "failure" }, new { @class = "btn-report btn btn-small btn-danger pull-left", id = "btn-report" })
              </div>
    }


</div>

@if (Model.Rows.Count != 0)
{
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Event Name</label>
            <label class="col-xs-12">@Model.Rows[0]["EventName"]</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Event L0cation</label>
            <label class="col-xs-12">@Model.Rows[0]["EventLocation"]</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Event Held On</label>
            <label class="col-xs-12">@Model.Rows[0]["EventHeldDate"]</label>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12"></div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Project Name</label>
            <label class="col-xs-12">@Model.Rows[0]["ProjectName"]</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Project Type</label>
            <label class="col-xs-12">@Model.Rows[0]["TypeName"]</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Project Location</label>
            <label class="col-xs-12">@Model.Rows[0]["ProjectLocation"]</label>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <label class="control-label">Total Applicable Units</label>
            <label class="col-xs-12">@Model.Rows[0]["TotalApplicableUnits"]</label>
        </div>
    </div>
}
<div class="table-responsive">
    <table class="table">
        <tr>
            <th>S.No</th>
            @foreach (System.Data.DataColumn col in Model.Columns)
            {
                if (!columnsToExclude.Contains(col.Caption))
                {
                    <th>@col.Caption</th>
                }
            }

            <th></th>
        </tr>
        @{ 
            int rowno = 1;
        }
        @foreach (System.Data.DataRow item in Model.Rows)
        {
            <tr>
                <td>@rowno</td>
                @foreach (System.Data.DataColumn col in Model.Columns)
                {
                    if (!columnsToExclude.Contains(col.Caption))
                    {
                        <td>
                            @*@Html.Display(item[col.Caption].ToString())*@
                            @item[col.Caption].ToString()
                        </td>
                    }
                }



                        <td class="position-relative" style="position:relative">
                            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal_@rowno">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">Are you sure cancel?</h4>
                                        </div>

                                        @using (Ajax.BeginForm("CancelBalloting", "Ballotings", new AjaxOptions { LoadingElementId = "loading_" + rowno + "" }))
    {
                                    <div class="modal-body">
                                        @Html.AntiForgeryToken()
                                        <input name="ballotingId" id="ballotingId" type="hidden" value="@item["BallotingId"].ToString()" />
                                        <label>Description</label>
                                        <input name="description" id="description" type="text" class="form-control" />

                                    </div>
                                    <div class="modal-footer">
                                        <span id="loading_@rowno" class="position-absolute" style="display:none; position:absolute; background-color:rgba(0,0,0,0.6); left:0; right:0; top:0; bottom:0; text-align:center;"><i class="fa fa-2x fa-spinner fa-spin"></i></span>
                                        <button type="submit" class="btn btn-default" id="modal-btn-si">Yes</button>
                                        <button type="button" class="btn btn-primary" data-dismiss="modal" id="modal-btn-no">No</button>
                                    </div>}

                                    </div>
                                    </div>
                            </div>

                            @*<span id="loading_@rowno" class="position-absolute" style="display:none; position:absolute; background-color:rgba(0,0,0,0.6); left:0; right:0; top:0; bottom:0; text-align:center;"><i class="fa fa-2x fa-spinner fa-spin"></i></span>*@
                           
                        <a href="javascript:void();" class="btn-cancel-balloting" data-target="mi-modal_@rowno"><i class="fa fa-trash"></i> Cancel</a>

                        </td>
            </tr>
            rowno++;
        }

    </table>
</div>
@*@Html.PagedListPager(Model, pageNumber => Url.Action("Index", new
    {
        pageNumber,
        officerName = Request.QueryString["keywords"]
    }))*@
@section scripts{
<script>
    $('.btn-cancel-balloting').on('click', function () {
        var target = $(this).data('target');
        
        $('#' + target + '').modal('show');

        //if (confirm('Are you sure to cancel this allocation?')) {
        //    $(this).closest('form').find('#description').val('description set by ejaz to delete');
        //    $(this).closest('form').submit();
        //    $(this).closest('row').remove();
        //}
    });
    $(function () {
        $('select#EventID').trigger('change');
    });
    $('.btn-report').on('click', function (e) {

        e.preventDefault();
        var url = $(this).attr('href');
        url = url.replace('eventid=0', 'eventid=' + $('select#EventID').val()).replace('projectId=0', 'projectId=' + $('select#ProjectID').val());
        var win = window.open(url, '_blank');
        if (win) {
            //Browser has allowed it to be opened
            win.focus();
        } else {
            //Browser has blocked it
            alert('Please allow popups for this website');
        }
    });

    $('select#EventID').on('change', function () {
        $('input#EventID').val($(this).val());
        $('#loader').toggle();
        $.get('/api/balloting/get-balloted-projects-for-events/' + $(this).val()).done(function (data) {
            if (data) {
                var html = '';
                $.each(data, function (key, value) {
                    console.log(value);
                    html += "<option value='" + value.id + "'>" + value.projectName + "</option>";
                });
                $('select#ProjectID').html(html);
                $('select#ProjectID').trigger('change');

                $('#viewresult').removeClass("disabled");
                $('.btn-report').removeClass("disabled");
            }
            else {
                $('#viewresult').addClass("disabled");
                $('.btn-report').addClass("disabled");
            }
            $('#loader').toggle();

        });
    });

    $('select#ProjectID').on('change', function () {
        $('input#ProjectID').val($(this).val());
    });
</script>
}